<h2>Numpy</h2>


In [66]:
import numpy as np 
import time

<h3>Creating array from list </h3>

In [67]:
arr_1D = np.array([1, 2, 3])
print("1D array is:", arr_1D)

1D array is: [1 2 3]


In [68]:
arr_2D = np.array([[1,2,3],[4,5,6]])
print ("2d array is : ", arr_2D)

2d array is :  [[1 2 3]
 [4 5 6]]


<h3>List vs Numpy array
</h3>

In [69]:
python_list = [1,2,3,4]
print("Python list Mul:",python_list * 2 )



Python list Mul: [1, 2, 3, 4, 1, 2, 3, 4]


In [70]:
np_array = np.array([1,2,3,4]) # Element wise Multiplecation
print("Python array Mul: ", np_array * 2)

Python array Mul:  [2 4 6 8]


In [71]:
# Record the start time for performance measurement
start = time.time()

# Create a Python list with 1 million elements, where each element is i*2
python_list = [i*2 for i in range(1000000)]
# Print the time taken for the list operation
print("\n list operation time: ", time.time() - start)

# Record a new start time for the next operation
start = time.time()

# Create a NumPy array with 1 million elements and multiply each by 2
# This demonstrates NumPy's vectorized operations
np_array = np.arange(1000000)*2
# Print the time taken for the NumPy operation
print("\n Numpy operation time: ", time.time() - start)


 list operation time:  0.05151510238647461

 Numpy operation time:  0.0030002593994140625


<h3>Creating array from scratch</h3>

In [72]:
zeros = np.zeros((3,2))
print("Zeros array:\n", zeros)

ones = np.ones((3,2))
print("ones array:\n", ones)   

full = np.full((3,2),7)
print("full array:\n", full)

random = np.random.random((3,2))
print("random array:\n", random)

sequence = np.arange(0,10,2)
print("sequence array:\n", sequence)

Zeros array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
full array:
 [[7 7]
 [7 7]
 [7 7]]
random array:
 [[0.67235822 0.65161895]
 [0.19168409 0.90105118]
 [0.56728363 0.85830009]]
sequence array:
 [0 2 4 6 8]


<h3>Vector, Matrix and Tensor</h3>

In [73]:
vector = np.array([1,2,3])
print("vector:",vector, type(vector))

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n" , matrix, type(matrix))

tensor = np.array ([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor: \n" , tensor,type(tensor))



vector: [1 2 3] <class 'numpy.ndarray'>
Matrix: 
 [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] <class 'numpy.ndarray'>


In [74]:
# Create example arrays
vector = np.array([1, 2, 3, 4])                    # 1D array (vector)
matrix = np.array([[1, 2, 3], [4, 5, 6]])          # 2D array (matrix)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D array (tensor)

# Function to determine array type
def check_array_type(arr):
    if not isinstance(arr, np.ndarray):
        return "Not a NumPy array"
    
    ndim = arr.ndim  # Get number of dimensions
    shape = arr.shape  # Get shape of array
    
    if ndim == 1:
        return f"Vector (1D array) with shape {shape}"
    elif ndim == 2:
        return f"Matrix (2D array) with shape {shape}"
    elif ndim >= 3:
        return f"Tensor ({ndim}D array) with shape {shape}"
    else:
        return "Scalar (0D array)"

# Check each array type
print("Array 1:", check_array_type(vector))
print("Array 2:", check_array_type(matrix))
print("Array 3:", check_array_type(tensor))

# check the number of dimensions directly
print("\nDirect dimension checks:")
print("Vector dimensions:", vector.ndim)
print("Matrix dimensions:", matrix.ndim)
print("Tensor dimensions:", tensor.ndim)

Array 1: Vector (1D array) with shape (4,)
Array 2: Matrix (2D array) with shape (2, 3)
Array 3: Tensor (3D array) with shape (2, 2, 2)

Direct dimension checks:
Vector dimensions: 1
Matrix dimensions: 2
Tensor dimensions: 3


<h2>Array Properties</h2>

In [75]:
arr= np.array([[1,2,3],[4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DataType", arr.dtype)


Shape (2, 3)
Dimension 2
Size 6
DataType int32


<h3>Array Reshaping</h3>

In [76]:
# Create a 1D array with values from 0 to 11
arr = np.arange(12)
print("Original array:", arr)

# Reshape the 1D array into a 3x4 2D array
reshaped = arr.reshape((3,4));
print("\n Reshaped array: \n", reshaped);

# Convert the 2D array back to 1D using flatten() - creates a copy
flattened = reshaped.flatten();
print("\n flattened array:", flattened)

# Convert the 2D array back to 1D using ravel() - creates a view when possible
raveled = reshaped.ravel();
print("\n raveled array:",raveled)



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [77]:
# Create a transposed version of the reshaped array
# Transposition switches rows and columns (or axes in general)
transposed = reshaped.T
print("Transposed array:\n", transposed)

Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


<h2>Numpy Array Operations</h2>

In [78]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing:", arr[2:7])
print("With Step : ",arr[1:8:2])
print("Negative indexing:",arr[-3])

Basic slicing: [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative indexing: 8


In [79]:
arr_2d = np.array([[1,2,3],
                  [2,3,4],
                  [3,4,5]])
print("Specific Element:",arr_2d[0,1])
print("Entire row:", arr_2d[1])
print("Entire column:", arr_2d[:,2])


Specific Element: 2
Entire row: [2 3 4]
Entire column: [3 4 5]


<h3>Sorting</h3>

In [80]:
unsorted = np.array([3,2,4,5,3,6,4,7,8,1])
print("Sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[1,4],[4,6],[2,5]]);
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis = 0))


Sorted Array: [1 2 3 3 4 4 5 6 7 8]
Sorted 2D array by column: 
 [[1 4]
 [2 5]
 [4 6]]


<h3>Filter</h3>

In [81]:
# Create a NumPy array with numbers from 1 to 9
numbers = np.array([1,2,3,4,5,6,7,8,9])
# Filter the array to get only even numbers using boolean indexing
even_num = numbers[numbers % 2 == 0 ]
# Print the resulting array of even numbers
print("Even numbers:", even_num)

Even numbers: [2 4 6 8]


<h3>Filter with mask</h3>

In [82]:
# Create a boolean mask where True indicates values greater than 5
mask = numbers > 5 
# Use the boolean mask to filter the array and print values greater than 5
print("Numbers greater than 5 :", numbers[mask])

Numbers greater than 5 : [6 7 8 9]


<h3>Fancy indexing vs np.where</h3>

In [106]:
indices = [0, 2 , 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("np Where :",numbers[where_result])

[1 3 5]
np Where : [6 7 8 9]


In [116]:
condition_array = np.where(numbers > 5,numbers*10, numbers*2)
print(condition_array)

[ 2  4  6  8 10 60 70 80 90]


<h3>Addting and Removing Data</h3>

In [120]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


<h3>Array compatibility</h3>

In [123]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("compatibility shapes", a.shape == b.shape)

compatibility shapes True


In [125]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [127]:
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)


[[1 2 7]
 [3 4 8]]


In [129]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
deleted = np.delete(arr, 3)
print(deleted)

[1 2 3 5 6 7]
